### ISSUE TITLE
Suggestion about string literals.

### ISSUE THREAD

**Issue by zillesc** [jmcasebeer/CS126WK#4]
I'd suggest making your string literals into 'public static final String  XWINS = "X wins!";'    We'll talk later in the class about why.

If you do so, you can modify your tests to use those literals.  We can argue about whether that is a good idea, because it prevents you from finding bugs if the literals are printed out incorrectly even though the logic is correct.

**Comment by jmcasebeer** [comment]
Thanks for the recommendation, for testing purposes I see how it will remove a point of failure(me typing in the win result wrong).
